services:
  postgres:
    container_name: postgres2
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123qwe
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    container_name: frontend2
    image: frontend-image:v1.0
    ports:
      - "4201:4200"
  
  backend:
    container_name: backend2
    image: backend-image:v1.0
    ports:
      - "7070:8080"
